// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `android_to_evdev_keycode`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveryEvent`

/// Get version string
Future<String> version() => RustApi.instance.api.crateApiVersion();

/// Check Tailscale status
Future<bool> checkTailscaleStatus() =>
    RustApi.instance.api.crateApiCheckTailscaleStatus();

/// Get list of peers on the tailnet
Future<List<PeerInfoDto>> getPeers() => RustApi.instance.api.crateApiGetPeers();

/// Connect to a peer
Future<ConnectionState> connectToPeer(
        {required String address, required int port}) =>
    RustApi.instance.api.crateApiConnectToPeer(address: address, port: port);

/// Send clipboard content to peer using KDE Connect protocol.
Future<void> sendClipboard(
        {required String address,
        required int port,
        required String content}) =>
    RustApi.instance.api
        .crateApiSendClipboard(address: address, port: port, content: content);

/// Get clipboard content from peer.
Future<String> getClipboard({required String address, required int port}) =>
    RustApi.instance.api.crateApiGetClipboard(address: address, port: port);

/// Send file to peer using KDE Share protocol.
Future<void> sendFile(
        {required String address,
        required int port,
        required String filePath}) =>
    RustApi.instance.api
        .crateApiSendFile(address: address, port: port, filePath: filePath);

/// List files in a remote directory using the file browse protocol.
Future<List<RemoteFileDto>> listRemoteFiles(
        {required String address,
        required int port,
        required String remotePath}) =>
    RustApi.instance.api.crateApiListRemoteFiles(
        address: address, port: port, remotePath: remotePath);

/// Request remote screen streaming.
Future<void> connectStreaming({required String address, required int port}) =>
    RustApi.instance.api.crateApiConnectStreaming(address: address, port: port);

/// Stop remote screen streaming.
Future<void> stopStreaming() => RustApi.instance.api.crateApiStopStreaming();

/// Check if streaming is active by inspecting the streaming handle.
bool isStreamingActive() => RustApi.instance.api.crateApiIsStreamingActive();

/// Get the current RTT to the streaming server in microseconds.
BigInt getStreamingRtt() => RustApi.instance.api.crateApiGetStreamingRtt();

/// Get detailed streaming session statistics.
StreamingStatsDto getStreamingStats() =>
    RustApi.instance.api.crateApiGetStreamingStats();

/// Receive queued H.264 frames from the streaming client.
Future<List<FrameDto>> receiveFrames({required BigInt timeoutMs}) =>
    RustApi.instance.api.crateApiReceiveFrames(timeoutMs: timeoutMs);

/// Send mouse event to remote, preferring the low-latency QUIC streaming channel.
///
/// Falls back to KDE Connect TCP protocol if streaming is not active.
Future<void> sendMouseEvent(
        {required String address,
        required int port,
        required double x,
        required double y,
        required int button,
        required bool isPressed}) =>
    RustApi.instance.api.crateApiSendMouseEvent(
        address: address,
        port: port,
        x: x,
        y: y,
        button: button,
        isPressed: isPressed);

/// Send keyboard event to remote, preferring the low-latency QUIC streaming channel.
///
/// Falls back to KDE Connect TCP protocol if streaming is not active.
Future<void> sendKeyboardEvent(
        {required String address,
        required int port,
        required int keyCode,
        required String text}) =>
    RustApi.instance.api.crateApiSendKeyboardEvent(
        address: address, port: port, keyCode: keyCode, text: text);

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
  const factory ConnectionState.connecting() = ConnectionState_Connecting;
  const factory ConnectionState.error(
    String field0,
  ) = ConnectionState_Error;
}

/// Frame data transfer object for Flutter/MediaCodec.
class FrameDto {
  final Uint8List data;
  final bool isKeyframe;
  final BigInt sequence;

  const FrameDto({
    required this.data,
    required this.isKeyframe,
    required this.sequence,
  });

  @override
  int get hashCode => data.hashCode ^ isKeyframe.hashCode ^ sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameDto &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          isKeyframe == other.isKeyframe &&
          sequence == other.sequence;
}

/// Peer information for display in Flutter
class PeerInfoDto {
  final String name;
  final String dnsName;
  final List<String> ips;
  final bool online;

  const PeerInfoDto({
    required this.name,
    required this.dnsName,
    required this.ips,
    required this.online,
  });

  @override
  int get hashCode =>
      name.hashCode ^ dnsName.hashCode ^ ips.hashCode ^ online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfoDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dnsName == other.dnsName &&
          ips == other.ips &&
          online == other.online;
}

/// Remote file metadata for the file browser.
class RemoteFileDto {
  final String name;
  final bool isDirectory;
  final BigInt size;
  final BigInt modified;

  const RemoteFileDto({
    required this.name,
    required this.isDirectory,
    required this.size,
    required this.modified,
  });

  @override
  int get hashCode =>
      name.hashCode ^ isDirectory.hashCode ^ size.hashCode ^ modified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDirectory == other.isDirectory &&
          size == other.size &&
          modified == other.modified;
}

/// Streaming statistics for display in Flutter.
class StreamingStatsDto {
  final double fps;
  final BigInt bitrateKbps;
  final BigInt e2ELatencyMs;
  final BigInt frameDrops;

  const StreamingStatsDto({
    required this.fps,
    required this.bitrateKbps,
    required this.e2ELatencyMs,
    required this.frameDrops,
  });

  @override
  int get hashCode =>
      fps.hashCode ^
      bitrateKbps.hashCode ^
      e2ELatencyMs.hashCode ^
      frameDrops.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamingStatsDto &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          bitrateKbps == other.bitrateKbps &&
          e2ELatencyMs == other.e2ELatencyMs &&
          frameDrops == other.frameDrops;
}
