// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `android_to_evdev_keycode`, `client_identity`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveryEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Set the persistent data directory for certs and state.
/// Must be called before `connect_streaming` for cert persistence.
Future<void> setDataDir({required String path}) =>
    RustApi.instance.api.crateApiSetDataDir(path: path);

/// Check if the LAN discovery service is active.
bool isDiscoveryActive() => RustApi.instance.api.crateApiIsDiscoveryActive();

/// Get version string
Future<String> version() => RustApi.instance.api.crateApiVersion();

/// Send Wake-on-LAN magic packet to wake a sleeping peer.
Future<void> sendWol(
        {required String macAddress, required String broadcastAddr}) =>
    RustApi.instance.api
        .crateApiSendWol(macAddress: macAddress, broadcastAddr: broadcastAddr);

/// Check Tailscale status
Future<bool> checkTailscaleStatus() =>
    RustApi.instance.api.crateApiCheckTailscaleStatus();

/// Get list of peers on the tailnet and LAN
Future<List<PeerInfoDto>> getPeers() => RustApi.instance.api.crateApiGetPeers();

/// Connect to a peer
Future<ConnectionState> connectToPeer(
        {required String address, required int port}) =>
    RustApi.instance.api.crateApiConnectToPeer(address: address, port: port);

/// Poll for incoming KDE Connect packets from the control connection.
/// Returns up to 16 queued packet JSON strings. Flutter should call this
/// periodically while connected to process server push messages (notifications,
/// clipboard sync, etc.).
Future<List<String>> pollIncomingPackets() =>
    RustApi.instance.api.crateApiPollIncomingPackets();

/// Send clipboard content to peer using KDE Connect protocol.
Future<void> sendClipboard(
        {required String address,
        required int port,
        required String content}) =>
    RustApi.instance.api
        .crateApiSendClipboard(address: address, port: port, content: content);

/// Get clipboard content from peer.
///
/// Tries the existing control connection first for lower latency.
/// Falls back to a new TCP connection if not currently connected.
Future<String> getClipboard({required String address, required int port}) =>
    RustApi.instance.api.crateApiGetClipboard(address: address, port: port);

/// Send file to peer using KDE Share protocol.
Future<void> sendFile(
        {required String address,
        required int port,
        required String filePath}) =>
    RustApi.instance.api
        .crateApiSendFile(address: address, port: port, filePath: filePath);

/// List files in a remote directory using the file browse protocol.
Future<List<RemoteFileDto>> listRemoteFiles(
        {required String address,
        required int port,
        required String remotePath}) =>
    RustApi.instance.api.crateApiListRemoteFiles(
        address: address, port: port, remotePath: remotePath);

/// Request remote screen streaming.
///
/// `monitor_index` selects which display to stream (0 = primary).
/// Pass `None` to use the default monitor.
Future<void> connectStreaming(
        {required String address, required int port, int? monitorIndex}) =>
    RustApi.instance.api.crateApiConnectStreaming(
        address: address, port: port, monitorIndex: monitorIndex);

/// Reset the reconnection backoff timer (e.g. after a successful manual connect).
void resetReconnectBackoff() =>
    RustApi.instance.api.crateApiResetReconnectBackoff();

/// Attempt to reconnect the current streaming session using exponential backoff.
Future<void> reconnectStreaming(
        {required String address,
        required int port,
        int? monitorIndex,
        required int attempt}) =>
    RustApi.instance.api.crateApiReconnectStreaming(
        address: address,
        port: port,
        monitorIndex: monitorIndex,
        attempt: attempt);

/// Stop remote screen streaming.
Future<void> stopStreaming() => RustApi.instance.api.crateApiStopStreaming();

/// Check if streaming is active using an atomic flag (no lock contention).
bool isStreamingActive() => RustApi.instance.api.crateApiIsStreamingActive();

/// Get the current RTT to the streaming server in microseconds.
BigInt getStreamingRtt() => RustApi.instance.api.crateApiGetStreamingRtt();

/// Get the current high-level status of the streaming session.
SessionStatus getSessionStatus() =>
    RustApi.instance.api.crateApiGetSessionStatus();

/// Get detailed streaming session statistics.
StreamingStatsDto getStreamingStats() =>
    RustApi.instance.api.crateApiGetStreamingStats();

/// List all trusted peers (certificate labels) from the active streaming session's
/// CertManager. Returns an empty list if no streaming session is active.
List<String> listTrustedPeers() =>
    RustApi.instance.api.crateApiListTrustedPeers();

/// Remove a trusted peer certificate by label. Returns true if the peer was
/// found and removed, false otherwise. Persists the change to disk.
bool forgetTrustedPeer({required String label}) =>
    RustApi.instance.api.crateApiForgetTrustedPeer(label: label);

/// Get the number of monitors available on the remote server.
///
/// F2: Multi-monitor support — returns 0 if detection fails or no display.
/// Get detailed list of monitors available on the remote server.
Future<List<MonitorInfoDto>> getMonitors(
        {required String address, required int port}) =>
    RustApi.instance.api.crateApiGetMonitors(address: address, port: port);

/// Get the number of monitors available on the remote server (legacy).
Future<int> getMonitorCount({required String address, required int port}) =>
    RustApi.instance.api.crateApiGetMonitorCount(address: address, port: port);

/// Execute a power management command on the remote server.
/// Supported actions: "sleep", "shutdown", "restart", "hibernate".
Future<void> sendPowerCommand(
        {required String address, required int port, required String action}) =>
    RustApi.instance.api
        .crateApiSendPowerCommand(address: address, port: port, action: action);

/// Execute a shell command on the remote server and return stdout + stderr + exit code.
Future<String> executeRemoteCommand(
        {required String address,
        required int port,
        required String command}) =>
    RustApi.instance.api.crateApiExecuteRemoteCommand(
        address: address, port: port, command: command);

/// Receive queued audio packets from the streaming client (F1: Audio Streaming).
///
/// Each audio packet contains raw Opus-encoded data (typically 20ms @ 48kHz stereo).
/// Returns up to `MAX_AUDIO_PACKETS_PER_RECEIVE` packets.
Future<List<Uint8List>> receiveAudio({required BigInt timeoutMs}) =>
    RustApi.instance.api.crateApiReceiveAudio(timeoutMs: timeoutMs);

/// Receive queued H.264 frames from the streaming client.
///
/// The `timeout_ms` parameter only applies to waiting for the FIRST frame.
/// After the first frame arrives, any additional queued frames are drained
/// immediately with `try_recv()` (no further timeout). Returns up to
/// `MAX_FRAMES_PER_RECEIVE` frames per call.
Future<List<FrameDto>> receiveFrames({required BigInt timeoutMs}) =>
    RustApi.instance.api.crateApiReceiveFrames(timeoutMs: timeoutMs);

/// Send mouse event to remote, preferring the low-latency QUIC streaming channel.
///
/// Falls back to KDE Connect TCP protocol if streaming is not active.
Future<void> sendMouseEvent(
        {required String address,
        required int port,
        required double x,
        required double y,
        required int button,
        required bool isPressed}) =>
    RustApi.instance.api.crateApiSendMouseEvent(
        address: address,
        port: port,
        x: x,
        y: y,
        button: button,
        isPressed: isPressed);

/// Send keyboard event to remote, preferring the low-latency QUIC streaming channel.
///
/// Falls back to KDE Connect TCP protocol if streaming is not active.
Future<void> sendKeyboardEvent(
        {required String address,
        required int port,
        required int keyCode,
        required String text}) =>
    RustApi.instance.api.crateApiSendKeyboardEvent(
        address: address, port: port, keyCode: keyCode, text: text);

/// Send gamepad state over the QUIC streaming channel.
///
/// `axes` contains 6 i16 values: [LX, LY, RX, RY, L2, R2] in range -32768..32767.
/// `buttons` is a 16-bit bitmask (A=0, B=1, X=2, Y=3, LB=4, RB=5,
/// Select=6, Start=7, Home=8, LSB=9, RSB=10, DPadUp=11..DPadRight=14).
/// Requires an active streaming session — no TCP fallback for gamepad.
Future<void> sendGamepadEvent(
        {required List<int> axes, required int buttons}) =>
    RustApi.instance.api.crateApiSendGamepadEvent(axes: axes, buttons: buttons);

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
  const factory ConnectionState.connecting() = ConnectionState_Connecting;
  const factory ConnectionState.error(
    LinuxLinkErrorDto field0,
  ) = ConnectionState_Error;
}

/// Frame data transfer object for Flutter/MediaCodec.
class FrameDto {
  final Uint8List data;
  final bool isKeyframe;
  final BigInt sequence;

  const FrameDto({
    required this.data,
    required this.isKeyframe,
    required this.sequence,
  });

  @override
  int get hashCode => data.hashCode ^ isKeyframe.hashCode ^ sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameDto &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          isKeyframe == other.isKeyframe &&
          sequence == other.sequence;
}

/// Structured error information for Flutter.
class LinuxLinkErrorDto {
  final int code;
  final String message;
  final bool isRetryable;

  const LinuxLinkErrorDto({
    required this.code,
    required this.message,
    required this.isRetryable,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ isRetryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinuxLinkErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          isRetryable == other.isRetryable;
}

/// Monitor information for display in Flutter
class MonitorInfoDto {
  final int index;
  final String name;
  final int width;
  final int height;
  final bool isPrimary;

  const MonitorInfoDto({
    required this.index,
    required this.name,
    required this.width,
    required this.height,
    required this.isPrimary,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      isPrimary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorInfoDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          isPrimary == other.isPrimary;
}

/// Peer information for display in Flutter
class PeerInfoDto {
  final String name;
  final String dnsName;
  final List<String> ips;
  final bool online;

  const PeerInfoDto({
    required this.name,
    required this.dnsName,
    required this.ips,
    required this.online,
  });

  @override
  int get hashCode =>
      name.hashCode ^ dnsName.hashCode ^ ips.hashCode ^ online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfoDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dnsName == other.dnsName &&
          ips == other.ips &&
          online == other.online;
}

/// Remote file metadata for the file browser.
class RemoteFileDto {
  final String name;
  final bool isDirectory;
  final BigInt size;
  final BigInt modified;

  const RemoteFileDto({
    required this.name,
    required this.isDirectory,
    required this.size,
    required this.modified,
  });

  @override
  int get hashCode =>
      name.hashCode ^ isDirectory.hashCode ^ size.hashCode ^ modified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDirectory == other.isDirectory &&
          size == other.size &&
          modified == other.modified;
}

@freezed
sealed class SessionStatus with _$SessionStatus {
  const SessionStatus._();

  const factory SessionStatus.disconnected() = SessionStatus_Disconnected;
  const factory SessionStatus.connecting() = SessionStatus_Connecting;
  const factory SessionStatus.active() = SessionStatus_Active;

  /// Connection is alive but RTT is extremely high or packets are being lost.
  const factory SessionStatus.stale({
    required BigInt rttMs,
  }) = SessionStatus_Stale;

  /// Attempting to automatically recover a lost connection.
  const factory SessionStatus.reconnecting({
    required int attempt,
    required BigInt nextRetryMs,
  }) = SessionStatus_Reconnecting;

  /// A fatal error occurred that cannot be automatically recovered.
  const factory SessionStatus.error(
    LinuxLinkErrorDto field0,
  ) = SessionStatus_Error;
}

/// Streaming statistics for display in Flutter.
class StreamingStatsDto {
  final double fps;
  final BigInt bitrateKbps;
  final BigInt e2ELatencyMs;
  final BigInt frameDrops;

  const StreamingStatsDto({
    required this.fps,
    required this.bitrateKbps,
    required this.e2ELatencyMs,
    required this.frameDrops,
  });

  @override
  int get hashCode =>
      fps.hashCode ^
      bitrateKbps.hashCode ^
      e2ELatencyMs.hashCode ^
      frameDrops.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamingStatsDto &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          bitrateKbps == other.bitrateKbps &&
          e2ELatencyMs == other.e2ELatencyMs &&
          frameDrops == other.frameDrops;
}
