// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustApiApiImplPlatform extends BaseApiImpl<RustApiWire> {
                  RustApiApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected ConnectionState dco_decode_connection_state(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected FrameDto dco_decode_frame_dto(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<FrameDto> dco_decode_list_frame_dto(dynamic raw);

@protected List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected PeerInfoDto dco_decode_peer_info_dto(dynamic raw);

@protected int dco_decode_u_16(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected FrameDto sse_decode_frame_dto(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<FrameDto> sse_decode_list_frame_dto(SseDeserializer deserializer);

@protected List<PeerInfoDto> sse_decode_list_peer_info_dto(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_connection_state(ConnectionState self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_frame_dto(FrameDto self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_frame_dto(List<FrameDto> self, SseSerializer serializer);

@protected void sse_encode_list_peer_info_dto(List<PeerInfoDto> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustApiWire implements BaseWire {
            RustApiWire.fromExternalLibrary(ExternalLibrary lib);

            
        }
        @JS('wasm_bindgen') external RustApiWasmModule get wasmModule;

        @JS() @anonymous extension type RustApiWasmModule._(JSObject _) implements JSObject {
            
        }
        