// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustApi extends BaseEntrypoint<RustApiApi, RustApiApiImpl, RustApiWire> {
  @internal
  static final instance = RustApi._();

  RustApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustApiApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustApiApiImpl, RustApiWire> get apiImplConstructor =>
      RustApiApiImpl.new;

  @override
  WireConstructor<RustApiWire> get wireConstructor =>
      RustApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1156727626;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'linux_link_android',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustApiApi extends BaseApi {
  Future<bool> crateApiCheckTailscaleStatus();

  Future<void> crateApiConnectStreaming(
      {required String address, required int port, int? monitorIndex});

  Future<ConnectionState> crateApiConnectToPeer(
      {required String address, required int port});

  Future<String> crateApiExecuteRemoteCommand(
      {required String address, required int port, required String command});

  bool crateApiForgetTrustedPeer({required String label});

  Future<String> crateApiGetClipboard(
      {required String address, required int port});

  Future<int> crateApiGetMonitorCount(
      {required String address, required int port});

  Future<List<PeerInfoDto>> crateApiGetPeers();

  BigInt crateApiGetStreamingRtt();

  StreamingStatsDto crateApiGetStreamingStats();

  Future<void> crateApiInitApp();

  bool crateApiIsStreamingActive();

  Future<List<RemoteFileDto>> crateApiListRemoteFiles(
      {required String address, required int port, required String remotePath});

  List<String> crateApiListTrustedPeers();

  Future<List<String>> crateApiPollIncomingPackets();

  Future<List<Uint8List>> crateApiReceiveAudio({required BigInt timeoutMs});

  Future<List<FrameDto>> crateApiReceiveFrames({required BigInt timeoutMs});

  Future<void> crateApiSendClipboard(
      {required String address, required int port, required String content});

  Future<void> crateApiSendFile(
      {required String address, required int port, required String filePath});

  Future<void> crateApiSendGamepadEvent(
      {required List<int> axes, required int buttons});

  Future<void> crateApiSendKeyboardEvent(
      {required String address,
      required int port,
      required int keyCode,
      required String text});

  Future<void> crateApiSendMouseEvent(
      {required String address,
      required int port,
      required double x,
      required double y,
      required int button,
      required bool isPressed});

  Future<void> crateApiSendPowerCommand(
      {required String address, required int port, required String action});

  Future<void> crateApiSetDataDir({required String path});

  Future<void> crateApiStopStreaming();

  Future<String> crateApiVersion();
}

class RustApiApiImpl extends RustApiApiImplPlatform implements RustApiApi {
  RustApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiCheckTailscaleStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCheckTailscaleStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCheckTailscaleStatusConstMeta =>
      const TaskConstMeta(
        debugName: "check_tailscale_status",
        argNames: [],
      );

  @override
  Future<void> crateApiConnectStreaming(
      {required String address, required int port, int? monitorIndex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_opt_box_autoadd_u_32(monitorIndex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConnectStreamingConstMeta,
      argValues: [address, port, monitorIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConnectStreamingConstMeta => const TaskConstMeta(
        debugName: "connect_streaming",
        argNames: ["address", "port", "monitorIndex"],
      );

  @override
  Future<ConnectionState> crateApiConnectToPeer(
      {required String address, required int port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_connection_state,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConnectToPeerConstMeta,
      argValues: [address, port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConnectToPeerConstMeta => const TaskConstMeta(
        debugName: "connect_to_peer",
        argNames: ["address", "port"],
      );

  @override
  Future<String> crateApiExecuteRemoteCommand(
      {required String address, required int port, required String command}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(command, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExecuteRemoteCommandConstMeta,
      argValues: [address, port, command],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExecuteRemoteCommandConstMeta =>
      const TaskConstMeta(
        debugName: "execute_remote_command",
        argNames: ["address", "port", "command"],
      );

  @override
  bool crateApiForgetTrustedPeer({required String label}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(label, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiForgetTrustedPeerConstMeta,
      argValues: [label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiForgetTrustedPeerConstMeta => const TaskConstMeta(
        debugName: "forget_trusted_peer",
        argNames: ["label"],
      );

  @override
  Future<String> crateApiGetClipboard(
      {required String address, required int port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetClipboardConstMeta,
      argValues: [address, port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetClipboardConstMeta => const TaskConstMeta(
        debugName: "get_clipboard",
        argNames: ["address", "port"],
      );

  @override
  Future<int> crateApiGetMonitorCount(
      {required String address, required int port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetMonitorCountConstMeta,
      argValues: [address, port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetMonitorCountConstMeta => const TaskConstMeta(
        debugName: "get_monitor_count",
        argNames: ["address", "port"],
      );

  @override
  Future<List<PeerInfoDto>> crateApiGetPeers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_peer_info_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetPeersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetPeersConstMeta => const TaskConstMeta(
        debugName: "get_peers",
        argNames: [],
      );

  @override
  BigInt crateApiGetStreamingRtt() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetStreamingRttConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetStreamingRttConstMeta => const TaskConstMeta(
        debugName: "get_streaming_rtt",
        argNames: [],
      );

  @override
  StreamingStatsDto crateApiGetStreamingStats() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_streaming_stats_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetStreamingStatsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetStreamingStatsConstMeta => const TaskConstMeta(
        debugName: "get_streaming_stats",
        argNames: [],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  bool crateApiIsStreamingActive() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsStreamingActiveConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsStreamingActiveConstMeta => const TaskConstMeta(
        debugName: "is_streaming_active",
        argNames: [],
      );

  @override
  Future<List<RemoteFileDto>> crateApiListRemoteFiles(
      {required String address,
      required int port,
      required String remotePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(remotePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_remote_file_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiListRemoteFilesConstMeta,
      argValues: [address, port, remotePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListRemoteFilesConstMeta => const TaskConstMeta(
        debugName: "list_remote_files",
        argNames: ["address", "port", "remotePath"],
      );

  @override
  List<String> crateApiListTrustedPeers() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiListTrustedPeersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListTrustedPeersConstMeta => const TaskConstMeta(
        debugName: "list_trusted_peers",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiPollIncomingPackets() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPollIncomingPacketsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPollIncomingPacketsConstMeta =>
      const TaskConstMeta(
        debugName: "poll_incoming_packets",
        argNames: [],
      );

  @override
  Future<List<Uint8List>> crateApiReceiveAudio({required BigInt timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReceiveAudioConstMeta,
      argValues: [timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReceiveAudioConstMeta => const TaskConstMeta(
        debugName: "receive_audio",
        argNames: ["timeoutMs"],
      );

  @override
  Future<List<FrameDto>> crateApiReceiveFrames({required BigInt timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_frame_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReceiveFramesConstMeta,
      argValues: [timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReceiveFramesConstMeta => const TaskConstMeta(
        debugName: "receive_frames",
        argNames: ["timeoutMs"],
      );

  @override
  Future<void> crateApiSendClipboard(
      {required String address, required int port, required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendClipboardConstMeta,
      argValues: [address, port, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendClipboardConstMeta => const TaskConstMeta(
        debugName: "send_clipboard",
        argNames: ["address", "port", "content"],
      );

  @override
  Future<void> crateApiSendFile(
      {required String address, required int port, required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendFileConstMeta,
      argValues: [address, port, filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendFileConstMeta => const TaskConstMeta(
        debugName: "send_file",
        argNames: ["address", "port", "filePath"],
      );

  @override
  Future<void> crateApiSendGamepadEvent(
      {required List<int> axes, required int buttons}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_16_loose(axes, serializer);
        sse_encode_u_32(buttons, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendGamepadEventConstMeta,
      argValues: [axes, buttons],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendGamepadEventConstMeta => const TaskConstMeta(
        debugName: "send_gamepad_event",
        argNames: ["axes", "buttons"],
      );

  @override
  Future<void> crateApiSendKeyboardEvent(
      {required String address,
      required int port,
      required int keyCode,
      required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_i_32(keyCode, serializer);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendKeyboardEventConstMeta,
      argValues: [address, port, keyCode, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendKeyboardEventConstMeta => const TaskConstMeta(
        debugName: "send_keyboard_event",
        argNames: ["address", "port", "keyCode", "text"],
      );

  @override
  Future<void> crateApiSendMouseEvent(
      {required String address,
      required int port,
      required double x,
      required double y,
      required int button,
      required bool isPressed}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_f_32(x, serializer);
        sse_encode_f_32(y, serializer);
        sse_encode_i_32(button, serializer);
        sse_encode_bool(isPressed, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendMouseEventConstMeta,
      argValues: [address, port, x, y, button, isPressed],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendMouseEventConstMeta => const TaskConstMeta(
        debugName: "send_mouse_event",
        argNames: ["address", "port", "x", "y", "button", "isPressed"],
      );

  @override
  Future<void> crateApiSendPowerCommand(
      {required String address, required int port, required String action}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(action, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendPowerCommandConstMeta,
      argValues: [address, port, action],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendPowerCommandConstMeta => const TaskConstMeta(
        debugName: "send_power_command",
        argNames: ["address", "port", "action"],
      );

  @override
  Future<void> crateApiSetDataDir({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSetDataDirConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetDataDirConstMeta => const TaskConstMeta(
        debugName: "set_data_dir",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiStopStreaming() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiStopStreamingConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStopStreamingConstMeta => const TaskConstMeta(
        debugName: "stop_streaming",
        argNames: [],
      );

  @override
  Future<String> crateApiVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVersionConstMeta => const TaskConstMeta(
        debugName: "version",
        argNames: [],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return const ConnectionState_Connected();
      case 1:
        return const ConnectionState_Disconnected();
      case 2:
        return const ConnectionState_Connecting();
      case 3:
        return ConnectionState_Error(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameDto dco_decode_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrameDto(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
      isKeyframe: dco_decode_bool(arr[1]),
      sequence: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FrameDto> dco_decode_list_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frame_dto).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_info_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RemoteFileDto> dco_decode_list_remote_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_remote_file_dto).toList();
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PeerInfoDto(
      name: dco_decode_String(arr[0]),
      dnsName: dco_decode_String(arr[1]),
      ips: dco_decode_list_String(arr[2]),
      online: dco_decode_bool(arr[3]),
    );
  }

  @protected
  RemoteFileDto dco_decode_remote_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RemoteFileDto(
      name: dco_decode_String(arr[0]),
      isDirectory: dco_decode_bool(arr[1]),
      size: dco_decode_u_64(arr[2]),
      modified: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  StreamingStatsDto dco_decode_streaming_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StreamingStatsDto(
      fps: dco_decode_f_64(arr[0]),
      bitrateKbps: dco_decode_u_64(arr[1]),
      e2ELatencyMs: dco_decode_u_64(arr[2]),
      frameDrops: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return const ConnectionState_Connected();
      case 1:
        return const ConnectionState_Disconnected();
      case 2:
        return const ConnectionState_Connecting();
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return ConnectionState_Error(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrameDto sse_decode_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_isKeyframe = sse_decode_bool(deserializer);
    var var_sequence = sse_decode_u_64(deserializer);
    return FrameDto(
        data: var_data, isKeyframe: var_isKeyframe, sequence: var_sequence);
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrameDto> sse_decode_list_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrameDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frame_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RemoteFileDto> sse_decode_list_remote_file_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RemoteFileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_remote_file_dto(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_dnsName = sse_decode_String(deserializer);
    var var_ips = sse_decode_list_String(deserializer);
    var var_online = sse_decode_bool(deserializer);
    return PeerInfoDto(
        name: var_name, dnsName: var_dnsName, ips: var_ips, online: var_online);
  }

  @protected
  RemoteFileDto sse_decode_remote_file_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modified = sse_decode_u_64(deserializer);
    return RemoteFileDto(
        name: var_name,
        isDirectory: var_isDirectory,
        size: var_size,
        modified: var_modified);
  }

  @protected
  StreamingStatsDto sse_decode_streaming_stats_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fps = sse_decode_f_64(deserializer);
    var var_bitrateKbps = sse_decode_u_64(deserializer);
    var var_e2ELatencyMs = sse_decode_u_64(deserializer);
    var var_frameDrops = sse_decode_u_64(deserializer);
    return StreamingStatsDto(
        fps: var_fps,
        bitrateKbps: var_bitrateKbps,
        e2ELatencyMs: var_e2ELatencyMs,
        frameDrops: var_frameDrops);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_connection_state(
      ConnectionState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConnectionState_Connected():
        sse_encode_i_32(0, serializer);
      case ConnectionState_Disconnected():
        sse_encode_i_32(1, serializer);
      case ConnectionState_Connecting():
        sse_encode_i_32(2, serializer);
      case ConnectionState_Error(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frame_dto(FrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_bool(self.isKeyframe, serializer);
    sse_encode_u_64(self.sequence, serializer);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frame_dto(
      List<FrameDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frame_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_info_dto(
      List<PeerInfoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_16_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putInt16List(self is Int16List ? self : Int16List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
      Int16List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_remote_file_dto(
      List<RemoteFileDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_remote_file_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.dnsName, serializer);
    sse_encode_list_String(self.ips, serializer);
    sse_encode_bool(self.online, serializer);
  }

  @protected
  void sse_encode_remote_file_dto(
      RemoteFileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_u_64(self.modified, serializer);
  }

  @protected
  void sse_encode_streaming_stats_dto(
      StreamingStatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.fps, serializer);
    sse_encode_u_64(self.bitrateKbps, serializer);
    sse_encode_u_64(self.e2ELatencyMs, serializer);
    sse_encode_u_64(self.frameDrops, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
