// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `update_streaming_rtt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveryEvent`, `StreamingHandle`


            /// Get version string
Future<String>  version() => RustApi.instance.api.crateVersion();

/// Check Tailscale status
Future<bool>  checkTailscaleStatus() => RustApi.instance.api.crateCheckTailscaleStatus();

/// Get list of peers on the tailnet
Future<List<PeerInfoDto>>  getPeers() => RustApi.instance.api.crateGetPeers();

/// Connect to a peer
Future<ConnectionState>  connectToPeer({required String address , required int port }) => RustApi.instance.api.crateConnectToPeer(address: address, port: port);

/// Send clipboard content to peer using KDE Connect protocol.
Future<void>  sendClipboard({required String address , required int port , required String content }) => RustApi.instance.api.crateSendClipboard(address: address, port: port, content: content);

/// Get clipboard content from peer.
Future<String>  getClipboard({required String address , required int port }) => RustApi.instance.api.crateGetClipboard(address: address, port: port);

/// Send file to peer using KDE Share protocol.
Future<void>  sendFile({required String address , required int port , required String filePath }) => RustApi.instance.api.crateSendFile(address: address, port: port, filePath: filePath);

/// Request remote screen streaming.
///
/// Connects to the server at `address:port` via QUIC, starts a background
/// receive task, and stores the session globally. Use `get_streaming_rtt`
/// to query the current RTT.
Future<void>  connectStreaming({required String address , required int port }) => RustApi.instance.api.crateConnectStreaming(address: address, port: port);

/// Stop remote screen streaming.
Future<void>  stopStreaming() => RustApi.instance.api.crateStopStreaming();

/// Check if streaming is active
Future<bool>  isStreamingActive() => RustApi.instance.api.crateIsStreamingActive();

/// Get the current RTT to the streaming server in microseconds.
///
/// Returns 0 if no streaming session is active.
/// This is a synchronous, lock-free read safe for the main thread.
BigInt  getStreamingRtt() => RustApi.instance.api.crateGetStreamingRtt();

/// Receive queued H.264 frames from the streaming client.
///
/// Polls the frame receiver channel with the given timeout (in milliseconds).
/// Returns up to 16 frames per call. Returns an empty list if no streaming
/// session is active or no frames are available.
Future<List<FrameDto>>  receiveFrames({required BigInt timeoutMs }) => RustApi.instance.api.crateReceiveFrames(timeoutMs: timeoutMs);

/// Send mouse event to remote using KDE mousepad protocol.
Future<void>  sendMouseEvent({required String address , required int port , required double x , required double y , required int button , required bool isPressed }) => RustApi.instance.api.crateSendMouseEvent(address: address, port: port, x: x, y: y, button: button, isPressed: isPressed);

/// Send keyboard event to remote using KDE mousepad protocol.
Future<void>  sendKeyboardEvent({required String address , required int port , required int keyCode , required String text }) => RustApi.instance.api.crateSendKeyboardEvent(address: address, port: port, keyCode: keyCode, text: text);

            @freezed
                sealed class ConnectionState with _$ConnectionState  {
                    const ConnectionState._();

                     const factory ConnectionState.connected() = ConnectionState_Connected;
 const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
 const factory ConnectionState.connecting() = ConnectionState_Connecting;
 const factory ConnectionState.error(  String field0,) = ConnectionState_Error;

                    

                    
                }

/// Frame data transfer object for Flutter/MediaCodec.
///
/// Note: No `timestamp` field is included because a monotonic `Instant` cannot
/// cross the FFI boundary in a meaningful way. Flutter should use `sequence`
/// for ordering and assign presentation timestamps via MediaCodec.
class FrameDto  {
                /// H.264 NAL unit data (including start codes).
final Uint8List data;
/// Whether this is a keyframe (IDR).
final bool isKeyframe;
/// Sequence number for ordering.
final BigInt sequence;

                const FrameDto({required this.data ,required this.isKeyframe ,required this.sequence ,});

                
                

                
        @override
        int get hashCode => data.hashCode^isKeyframe.hashCode^sequence.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FrameDto &&
                runtimeType == other.runtimeType
                && data == other.data&& isKeyframe == other.isKeyframe&& sequence == other.sequence;
        
            }

/// Peer information for display in Flutter
class PeerInfoDto  {
                final String name;
final String dnsName;
final List<String> ips;
final bool online;

                const PeerInfoDto({required this.name ,required this.dnsName ,required this.ips ,required this.online ,});

                
                

                
        @override
        int get hashCode => name.hashCode^dnsName.hashCode^ips.hashCode^online.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PeerInfoDto &&
                runtimeType == other.runtimeType
                && name == other.name&& dnsName == other.dnsName&& ips == other.ips&& online == other.online;
        
            }
            